name = "gavinpower-dot-dev"
compatibility_date = "2024-04-23"
pages_build_output_dir = "./dist"

[vars]
nodejs_compat = true

[[d1_databases]]
binding = "D1"
database_name = "website"
database_id = "f789dbca-fe88-4889-9571-d1f0eaa433bf"